name: Node.js CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - working-directory: backend
        run: docker build -t back .
      - run: docker kill back || true
      - run: docker rm back || true
      - run: docker run -p 9000:9000 -d --name back back
      - working-directory: frontend
        run: docker build -t front .
      - run: docker kill front || front 
      - run: docker rm front || true
      - run: docker run -p 8080:8080 -d --name front frontz
